import { StyleSheet } from "react-native";
import { THEME } from "../../../theme";

export const styles = StyleSheet.create({
  mainContainer: {
    position: "absolute",
    zIndex: 10,
    height: "100%",
    width: "100%",
    backgroundColor: "white",
  },
  upperContainer: {
    paddingVertical: 60,
    alignItems: "center",
    backgroundColor: "black",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  newBetTitle: {
    color: "white",
    fontSize: 20,
    fontFamily: "montserratBold",
    borderBottomWidth: 0.5,
    borderBottomColor: THEME.COLORS.DARK_GRAY,
    width: "100%",
    textAlign: "center",
    paddingBottom: 20,
  },
  teamsContainer: {
    height: 140,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 40,
    borderBottomWidth: 0.5,
    borderBottomColor: THEME.COLORS.DARK_GRAY,
  },
  teamContainer: {
    alignItems: "center",
  },
  iconContainer: {
    backgroundColor: "white",
    width: 60,
    height: 60,
    borderRadius: 20,
    textAlign: "center",
    verticalAlign: "middle",
    fontSize: 30,
  },
  vsText: {
    backgroundColor: "white",
    height: 30,
    width: 30,
    textAlign: "center",
    verticalAlign: "middle",
    borderRadius: 30,
    fontFamily: "montserratBold",
    fontSize: 12,
  },
  teamName: {
    color: "white",
    textAlign: "center",
    fontFamily: "montserratBold",
    fontSize: 15,
  },

  titleBet: {
    fontSize: 20,
    fontFamily: "montserratBold",
    marginTop: 40,
    marginLeft: 20,
    marginBottom: 10,
  },

  betIconContainer: {
    textAlign: "center",
    verticalAlign: "middle",
    fontSize: 30,
  },
  betTeamName: {
    textAlign: "center",
    fontFamily: "montserratBold",
    fontSize: 15,
    color: "black",
    maxWidth: 130,
  },
  infoContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 20,
    width: "100%",
  },
  subtitle: {
    color: THEME.COLORS.DARK_GRAY,
    fontSize: 15,
    marginLeft: 10,
    fontFamily: "montserratBold",
    maxWidth: 150,
  },
  subtitleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  betContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 0.5,
    borderTopColor: THEME.COLORS.DARK_GRAY,
    borderBottomWidth: 0.5,
    borderBottomColor: THEME.COLORS.DARK_GRAY,
    paddingVertical: 20,
    paddingHorizontal: 30,
  },
  slidersContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  sliderButton: {
    height: 35,
    width: 35,
    textAlign: "center",
    verticalAlign: "middle",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "black",
    fontSize: 20,
  },
  betTeamContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  goalsCounter: {
    fontSize: 20,
    backgroundColor: THEME.COLORS.LIGHT_GRAY,
    padding: 10,
    borderRadius: 10,
    width: 50,
    height: 50,
    textAlign: "center",
    verticalAlign: "middle",
    fontFamily: "montserratBold",
  },
  concludeBet: {
    backgroundColor: THEME.COLORS.BLUE,
    alignSelf: "center",
    marginTop: 50,
    paddingVertical: 20,
    paddingHorizontal: 100,
    borderRadius: 100,
    fontSize: 15,
    color: "white",
    fontFamily: "montserratBold",
  },
  closeIconContainer: {
    width: "100%",
    alignItems: "flex-end",
    paddingRight: 30,
    marginBottom: -32,
    zIndex: 100,
  },
  buttonClose: {
    height: 40,
    width: 40,
    padding: 10,
  },
  closeIcon: {
    flex: 1,
    height: "100%",
    width: "100%",
    resizeMode: "contain",
  },
  activityIndicator: {
    marginTop: 30,
  },
});
